name: Debug - Release Windows Exec
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          python setup.py build_ext --inplace
          pip install .
    - name: Build exec
      id: build-exec
      run: |
        pyinstaller --clean --noupx -y --debug all pewpew.debug.spec

    - uses: actions/upload-artifact@v2
      with:
        name: pyinstaller_build
        path: ./dist/
